version: 2
services:
  es:
    image: elasticsearch:7.1.1
    cpu_shares: 100
    mem_limit: 262144000
  web:
    image: khornlund/haggle
    cpu_shares: 100
    mem_limit: 262144000
    ports:
      - "80:5000"
    links:
      - es
